/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FHIRVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getResourceTypeString"
      | "getVerificationModeString"
      | "verify"
      | "verifyFHIRResource"
      | "verifyFHIRResourceWithReference"
      | "verifyFHIRResourceWithSelectiveDisclosure"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FHIRResourceVerified"): EventFragment;

  encodeFunctionData(
    functionFragment: "getResourceTypeString",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationModeString",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyFHIRResource",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      BigNumberish,
      [BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyFHIRResourceWithReference",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      BigNumberish,
      [BigNumberish, BigNumberish],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyFHIRResourceWithSelectiveDisclosure",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      BigNumberish,
      [BigNumberish, BigNumberish]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getResourceTypeString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationModeString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyFHIRResource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyFHIRResourceWithReference",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyFHIRResourceWithSelectiveDisclosure",
    data: BytesLike
  ): Result;
}

export namespace FHIRResourceVerifiedEvent {
  export type InputTuple = [
    verifier: AddressLike,
    resourceType: BigNumberish,
    expectedHash: [BigNumberish, BigNumberish],
    verificationMode: BigNumberish,
    result: boolean
  ];
  export type OutputTuple = [
    verifier: string,
    resourceType: bigint,
    expectedHash: [bigint, bigint],
    verificationMode: bigint,
    result: boolean
  ];
  export interface OutputObject {
    verifier: string;
    resourceType: bigint;
    expectedHash: [bigint, bigint];
    verificationMode: bigint;
    result: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHIRVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): FHIRVerifier;
  waitForDeployment(): Promise<this>;

  interface: FHIRVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getResourceTypeString: TypedContractMethod<
    [resourceType: BigNumberish],
    [string],
    "view"
  >;

  getVerificationModeString: TypedContractMethod<
    [mode: BigNumberish],
    [string],
    "view"
  >;

  verify: TypedContractMethod<
    [
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      input: BigNumberish[]
    ],
    [boolean],
    "view"
  >;

  verifyFHIRResource: TypedContractMethod<
    [
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      resourceType: BigNumberish,
      expectedHash: [BigNumberish, BigNumberish]
    ],
    [boolean],
    "nonpayable"
  >;

  verifyFHIRResourceWithReference: TypedContractMethod<
    [
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      resourceType: BigNumberish,
      expectedHash: [BigNumberish, BigNumberish],
      referencedResourceType: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  verifyFHIRResourceWithSelectiveDisclosure: TypedContractMethod<
    [
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      resourceType: BigNumberish,
      expectedHash: [BigNumberish, BigNumberish]
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getResourceTypeString"
  ): TypedContractMethod<[resourceType: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getVerificationModeString"
  ): TypedContractMethod<[mode: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      input: BigNumberish[]
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyFHIRResource"
  ): TypedContractMethod<
    [
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      resourceType: BigNumberish,
      expectedHash: [BigNumberish, BigNumberish]
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyFHIRResourceWithReference"
  ): TypedContractMethod<
    [
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      resourceType: BigNumberish,
      expectedHash: [BigNumberish, BigNumberish],
      referencedResourceType: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyFHIRResourceWithSelectiveDisclosure"
  ): TypedContractMethod<
    [
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      resourceType: BigNumberish,
      expectedHash: [BigNumberish, BigNumberish]
    ],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "FHIRResourceVerified"
  ): TypedContractEvent<
    FHIRResourceVerifiedEvent.InputTuple,
    FHIRResourceVerifiedEvent.OutputTuple,
    FHIRResourceVerifiedEvent.OutputObject
  >;

  filters: {
    "FHIRResourceVerified(address,uint8,uint256[2],uint8,bool)": TypedContractEvent<
      FHIRResourceVerifiedEvent.InputTuple,
      FHIRResourceVerifiedEvent.OutputTuple,
      FHIRResourceVerifiedEvent.OutputObject
    >;
    FHIRResourceVerified: TypedContractEvent<
      FHIRResourceVerifiedEvent.InputTuple,
      FHIRResourceVerifiedEvent.OutputTuple,
      FHIRResourceVerifiedEvent.OutputObject
    >;
  };
}
