/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iCompensationOldSol from "./ICompensationOld.sol";
export { ICompensation__factory } from "./ICompensation__factory";
export { IDataRegistry__factory } from "./IDataRegistry__factory";
export { IZKPVerifier__factory } from "./IZKPVerifier__factory";
