/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZKPVerifier,
  IZKPVerifierInterface,
} from "../../interfaces/IZKPVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[]",
        name: "input",
        type: "uint256[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZKPVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IZKPVerifierInterface {
    return new Interface(_abi) as IZKPVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZKPVerifier {
    return new Contract(address, _abi, runner) as unknown as IZKPVerifier;
  }
}
