/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SenderCreator070,
  SenderCreator070Interface,
} from "../SenderCreator070";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "initCode",
        type: "bytes",
      },
    ],
    name: "createSender",
    outputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class SenderCreator070__factory {
  static readonly abi = _abi;
  static createInterface(): SenderCreator070Interface {
    return new Interface(_abi) as SenderCreator070Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SenderCreator070 {
    return new Contract(address, _abi, runner) as unknown as SenderCreator070;
  }
}
