/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICompensation__factory } from "./ICompensation__factory";
export { ICompensation1__factory } from "./ICompensation1__factory";
export { IDataRegistry__factory } from "./IDataRegistry__factory";
