/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as consentSol from "./Consent.sol";
export type { consentSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as library from "./library";
export type { library };
export type { Compensation } from "./Compensation";
export type { Compensation1 } from "./Compensation1";
export type { DataAccess } from "./DataAccess";
export type { DataRegistry } from "./DataRegistry";
export type { DataRegistry1 } from "./DataRegistry1";
export type { DataSharing } from "./DataSharing";
export type { DidAccessControl } from "./DidAccessControl";
export type { DidAuth } from "./DidAuth";
export type { DidAuth1 } from "./DidAuth1";
export type { DidIssuer } from "./DidIssuer";
export type { DidRegistry } from "./DidRegistry";
export type { DidVerifier } from "./DidVerifier";
export type { Token } from "./Token";
